### ISSUE TITLE
AUTOMATION - Add organization repo labels to all repos individually

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/.github#13]
## Description
I added a ton of repo labels to the Github organization, but apparently they only add to new repos. So damn depressing. Can we write a script that would automatically copy these labels I worked to hard on to all of our 50-ish existing repositories so I don't have to do this manually?

Organization level repo labels: https://github.com/organizations/OpenMined/settings/labels
Description of the problem: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization

## Are you interested in working on this improvement yourself?
- No, but I think @simcof would be interested.

## Additional Context
None

**Comment by Nilanshrajput** [comment]
> Organization level repo labels: https://github.com/organizations/OpenMined/settings/labels
this link is giving 404 error, is it due to some permissions?

**Comment by cereallarceny** [comment]
Yes. Only myself, Trask, or Ben can do this issue.

**Comment by Nilanshrajput** [comment]
Hi @cereallarceny  I created a script for adding labels across the all OpenMined repos, https://gist.github.com/Nilanshrajput/202c9fc6b8e251ea4699e7e6b9b2144a

**Comment by tcp** [comment]
Hey @Nilanshrajput! Thank you :)

Unfortunately, I can't use your script to replace all the labels -- we don't want to delete existing labels for the projects, just rename where appropriate.

**Comment by Nilanshrajput** [comment]
@tcp you can just comment out delete label function, it will just add the labels to existing set of labels, and will overwrite if same name!

**Comment by tcp** [comment]
That's the thing -- we have to manually pass through every repo and make a judgment call if an existing label fits any of the new labels.

What I'm doing is adding all the labels through the script to all repo's and going through each of them renaming where appropriate :)

**Comment by tcp** [comment]
@cereallarceny hey bud, I saw some interesting labels in some repo's, like `Duplicate`, `Question` and `Wont fix`. What do you think about incorporating them?

**Comment by tcp** [comment]
@cereallarceny I've just finished modifying labels for all OpenMined repos (minus PySyft). I ran a script to update the labels where it was required and create the ones that were missing.

Labels that remained unchanged and are set by default or interesting:
- wontfix
- help wanted
- invalid
- duplicate
- design
- build
- CI
- API
- release
- GSOC
- priority (/GridNetwork -- ask @vkkhare to set new priority label)

**Comment by cereallarceny** [comment]
Done by @tcp
